language: java
jdk: openjdk8

before_install:
  - chmod +x ./gradlew

script:
  - ./gradlew --no-daemon assemble test

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

addons:
  apt:
    packages:
      - openjdk-8-jdk