-- begin REF_CURRENCY
create table REF_CURRENCY (
    CODE varchar2(255 char),
    UUID varchar2(32),
    VERSION number(10),
    CREATE_TS timestamp,
    CREATED_BY varchar2(50 char),
    UPDATE_TS timestamp,
    UPDATED_BY varchar2(50 char),
    DELETE_TS timestamp,
    DELETED_BY varchar2(50 char),
    --
    NAME varchar2(255 char),
    --
    primary key (CODE)
)^
-- end REF_CURRENCY
-- begin REF_SELLER
create table REF_SELLER (
    ID number(19),
    UUID varchar2(32),
    VERSION number(10),
    CREATE_TS timestamp,
    CREATED_BY varchar2(50 char),
    UPDATE_TS timestamp,
    UPDATED_BY varchar2(50 char),
    DELETE_TS timestamp,
    DELETED_BY varchar2(50 char),
    --
    NAME varchar2(255 char),
    --
    primary key (ID)
)^
-- end REF_SELLER
-- begin REF_CAR_GARAGE_TOKEN
create table REF_CAR_GARAGE_TOKEN (
    ID varchar2(32),
    --
    TITLE varchar2(50 char) not null,
    TOKEN varchar2(20 char) not null,
    DESCRIPTION varchar2(200 char),
    LAST_USAGE timestamp,
    --
    primary key (ID)
)^
-- end REF_CAR_GARAGE_TOKEN
-- begin REF_ALLOCATED_CAR
create table REF_ALLOCATED_CAR (
    ID varchar2(32),
    --
    VIN varchar2(255 char),
    MODEL_ID varchar2(32),
    COLOUR_NAME varchar2(255 char),
    DRIVER_NAME varchar2(255 char),
    ALLOC_TS timestamp,
    --
    primary key (ID)
)^
-- end REF_ALLOCATED_CAR
-- begin REF_CAR_TOKEN
create table REF_CAR_TOKEN (
    ID varchar2(32),
    --
    TOKEN varchar2(255 char),
    REPAIR_ID varchar2(32),
    GARAGE_TOKEN_ID varchar2(32),
    --
    primary key (ID)
)^
-- end REF_CAR_TOKEN
-- begin REF_DRIVER_ALLOC
create table REF_DRIVER_ALLOC (
    ID varchar2(32),
    CREATE_TS timestamp,
    CREATED_BY varchar2(50 char),
    --
    DRIVER_ID varchar2(32),
    CAR_ID varchar2(32),
    --
    primary key (ID)
)^
-- end REF_DRIVER_ALLOC
-- begin REF_IK_ORDER_LINE_TAG
create table REF_IK_ORDER_LINE_TAG (
    ID number(19) generated by default on null as identity /** Supported from version 12c **/,
    --
    ORDER_LINE_ID number(19),
    NAME varchar2(255 char),
    --
    primary key (ID)
)^
-- end REF_IK_ORDER_LINE_TAG
-- begin REF_IK_ORDER_LINE
create table REF_IK_ORDER_LINE (
    ID number(19) generated by default on null as identity /** Supported from version 12c **/,
    --
    ORDER_ID number(19),
    PRODUCT varchar2(255 char),
    --
    primary key (ID)
)^
-- end REF_IK_ORDER_LINE
-- begin REF_IK_CUSTOMER
create table REF_IK_CUSTOMER (
    ID number(19) generated by default on null as identity /** Supported from version 12c **/,
    --
    NAME varchar2(255 char),
    --
    primary key (ID)
)^
-- end REF_IK_CUSTOMER
-- begin REF_IK_ORDER
create table REF_IK_ORDER (
    ID number(19) generated by default on null as identity /** Supported from version 12c **/,
    --
    ORDER_DATE timestamp,
    CUSTOMER_ID number(19),
    --
    primary key (ID)
)^
-- end REF_IK_ORDER
-- begin REF_CAR_DOCUMENTATION
create table REF_CAR_DOCUMENTATION (
    ID varchar2(32),
    VERSION number(10) not null,
    CREATE_TS timestamp,
    CREATED_BY varchar2(50 char),
    UPDATE_TS timestamp,
    UPDATED_BY varchar2(50 char),
    DELETE_TS timestamp,
    DELETED_BY varchar2(50 char),
    --
    TITLE varchar2(255 char),
    --
    primary key (ID)
)^
-- end REF_CAR_DOCUMENTATION
-- begin REF_MODEL
create table REF_MODEL (
    ID varchar2(32),
    VERSION number(10) not null,
    CREATE_TS timestamp,
    CREATED_BY varchar2(50 char),
    UPDATE_TS timestamp,
    UPDATED_BY varchar2(50 char),
    DELETE_TS timestamp,
    DELETED_BY varchar2(50 char),
    DTYPE varchar2(100 char),
    --
    NAME varchar2(255 char),
    MANUFACTURER varchar2(255 char),
    NUMBER_OF_SEATS number(10),
    --
    -- from ref$ExtModel
    LAUNCH_YEAR number(10),
    --
    primary key (ID)
)^
-- end REF_MODEL
-- begin REF_DRIVER_GROUP
create table REF_DRIVER_GROUP (
    ID varchar2(32),
    VERSION number(10) not null,
    CREATE_TS timestamp,
    CREATED_BY varchar2(50 char),
    UPDATE_TS timestamp,
    UPDATED_BY varchar2(50 char),
    DELETE_TS timestamp,
    DELETED_BY varchar2(50 char),
    --
    NAME varchar2(255 char),
    IN_USE char(1),
    --
    primary key (ID)
)^
-- end REF_DRIVER_GROUP
-- begin REF_COLOUR
create table REF_COLOUR (
    ID varchar2(32),
    VERSION number(10) not null,
    CREATE_TS timestamp,
    CREATED_BY varchar2(50 char),
    UPDATE_TS timestamp,
    UPDATED_BY varchar2(50 char),
    DELETE_TS timestamp,
    DELETED_BY varchar2(50 char),
    --
    NAME varchar2(255 char),
    DESCRIPTION varchar2(255 char),
    --
    primary key (ID)
)^
-- end REF_COLOUR
-- begin REF_PLACE
create table REF_PLACE (
    ID varchar2(32),
    VERSION number(10) not null,
    CREATE_TS timestamp,
    CREATED_BY varchar2(50 char),
    UPDATE_TS timestamp,
    UPDATED_BY varchar2(50 char),
    DELETE_TS timestamp,
    DELETED_BY varchar2(50 char),
    --
    NAME varchar2(255 char),
    --
    primary key (ID)
)^
-- end REF_PLACE
-- begin DEBT_CASE
create table DEBT_CASE (
    ID varchar2(32),
    VERSION number(10) not null,
    CREATE_TS timestamp,
    CREATED_BY varchar2(50 char),
    UPDATE_TS timestamp,
    UPDATED_BY varchar2(50 char),
    DELETE_TS timestamp,
    DELETED_BY varchar2(50 char),
    --
    TEST1 varchar2(50 char),
    TEST2 varchar2(50 char),
    TEST3 varchar2(50 char),
    TEST4 varchar2(50 char),
    TEST5 varchar2(50 char),
    TEST6 varchar2(50 char),
    TEST7 varchar2(50 char),
    TEST8 varchar2(50 char),
    TEST9 varchar2(50 char),
    TEST10 varchar2(50 char),
    DEBTOR_ID varchar2(32) not null,
    --
    primary key (ID)
)^
-- end DEBT_CASE
-- begin REF_CAR_DETAILS_ITEM
create table REF_CAR_DETAILS_ITEM (
    ID varchar2(32),
    VERSION number(10) not null,
    CREATE_TS timestamp,
    CREATED_BY varchar2(50 char),
    UPDATE_TS timestamp,
    UPDATED_BY varchar2(50 char),
    DELETE_TS timestamp,
    DELETED_BY varchar2(50 char),
    --
    CAR_DETAILS_ID varchar2(32),
    INFO varchar2(255 char),
    --
    primary key (ID)
)^
-- end REF_CAR_DETAILS_ITEM
-- begin REF_DRIVER
create table REF_DRIVER (
    ID varchar2(32),
    VERSION number(10) not null,
    CREATE_TS timestamp,
    CREATED_BY varchar2(50 char),
    UPDATE_TS timestamp,
    UPDATED_BY varchar2(50 char),
    DELETE_TS timestamp,
    DELETED_BY varchar2(50 char),
    DTYPE varchar2(100 char),
    --
    COUNTRY varchar2(255 char),
    STATE varchar2(255 char),
    CITY varchar2(255 char),
    STREET varchar2(255 char),
    ZIP varchar2(255 char),
    HOUSENUMBER varchar2(255 char),
    FLATNUMBER varchar2(255 char),
    LATITUDE float,
    LONGITUDE float,
    ADDRESS_SINCE date,
    PLACE_ID varchar2(32),
    --
    NAME varchar2(255 char),
    CALLSIGN_ID varchar2(32),
    DRIVER_GROUP_ID varchar2(32),
    STATUS integer,
    PLATFORM_ENTITY_ID varchar2(32),
    --
    -- from ref$ExtDriver
    INFO varchar2(50 char),
    NOTES clob,
    --
    primary key (ID)
)^
-- end REF_DRIVER
-- begin REF_INSURANCE_CASE
create table REF_INSURANCE_CASE (
    ID varchar2(32),
    VERSION number(10) not null,
    CREATE_TS timestamp,
    CREATED_BY varchar2(50 char),
    UPDATE_TS timestamp,
    UPDATED_BY varchar2(50 char),
    DELETE_TS timestamp,
    DELETED_BY varchar2(50 char),
    --
    CAR_ID varchar2(32),
    DESCRIPTION varchar2(255 char),
    --
    primary key (ID)
)^
-- end REF_INSURANCE_CASE
-- begin REF_SAMPLE_PLATFORM_ENTITY
create table REF_SAMPLE_PLATFORM_ENTITY (
    ID varchar2(32),
    VERSION number(10) not null,
    CREATE_TS timestamp,
    CREATED_BY varchar2(50 char),
    UPDATE_TS timestamp,
    UPDATED_BY varchar2(50 char),
    DELETE_TS timestamp,
    DELETED_BY varchar2(50 char),
    --
    NAME varchar2(255 char),
    --
    primary key (ID)
)^
-- end REF_SAMPLE_PLATFORM_ENTITY
-- begin DEBT_DEBTOR
create table DEBT_DEBTOR (
    ID varchar2(32),
    VERSION number(10) not null,
    CREATE_TS timestamp,
    CREATED_BY varchar2(50 char),
    UPDATE_TS timestamp,
    UPDATED_BY varchar2(50 char),
    DELETE_TS timestamp,
    DELETED_BY varchar2(50 char),
    --
    TITLE varchar2(50 char) not null,
    --
    primary key (ID)
)^
-- end DEBT_DEBTOR
-- begin REF_REPAIR
create table REF_REPAIR (
    ID varchar2(32),
    VERSION number(10) not null,
    CREATE_TS timestamp,
    CREATED_BY varchar2(50 char),
    UPDATE_TS timestamp,
    UPDATED_BY varchar2(50 char),
    DELETE_TS timestamp,
    DELETED_BY varchar2(50 char),
    --
    CAR_ID varchar2(32),
    INSURANCE_CASE_ID varchar2(32),
    DESCRIPTION varchar2(255 char),
    REPAIR_DATE date,
    DB1_CUSTOMER_ID number(19),
    --
    primary key (ID)
)^
-- end REF_REPAIR
-- begin REF_PRICING_REGION
create table REF_PRICING_REGION (
    ID varchar2(32),
    VERSION number(10) not null,
    CREATE_TS timestamp,
    CREATED_BY varchar2(50 char),
    UPDATE_TS timestamp,
    UPDATED_BY varchar2(50 char),
    DELETE_TS timestamp,
    DELETED_BY varchar2(50 char),
    --
    NAME varchar2(50 char) not null,
    PARENT_ID varchar2(32),
    --
    primary key (ID)
)^
-- end REF_PRICING_REGION
-- begin REF_PLANT
create table REF_PLANT (
    ID varchar2(32),
    VERSION number(10) not null,
    CREATE_TS timestamp,
    CREATED_BY varchar2(50 char),
    UPDATE_TS timestamp,
    UPDATED_BY varchar2(50 char),
    DELETE_TS timestamp,
    DELETED_BY varchar2(50 char),
    DTYPE varchar2(100 char),
    --
    NAME varchar2(255 char),
    DOC_ID varchar2(32),
    --
    -- from ref$CustomExtPlant
    ADDITIONAL_INFO varchar2(255 char),
    --
    -- from ref$ExtPlant
    NUMBER_IN_1C varchar2(255 char),
    --
    primary key (ID)
)^
-- end REF_PLANT
-- begin REF_DRIVER_LICENSE
create table REF_DRIVER_LICENSE (
    ID varchar2(32),
    VERSION number(10) not null,
    CREATE_TS timestamp,
    CREATED_BY varchar2(50 char),
    UPDATE_TS timestamp,
    UPDATED_BY varchar2(50 char),
    DELETE_TS timestamp,
    DELETED_BY varchar2(50 char),
    --
    DRIVER_ID varchar2(32) not null,
    CAR_ID varchar2(32) not null,
    PRIORITY number(10) not null,
    --
    primary key (ID)
)^
-- end REF_DRIVER_LICENSE
-- begin REF_DRIVER_CALLSIGN
create table REF_DRIVER_CALLSIGN (
    ID varchar2(32),
    VERSION number(10) not null,
    CREATE_TS timestamp,
    CREATED_BY varchar2(50 char),
    UPDATE_TS timestamp,
    UPDATED_BY varchar2(50 char),
    DELETE_TS timestamp,
    DELETED_BY varchar2(50 char),
    --
    CALLSIGN varchar2(50 char),
    --
    primary key (ID)
)^
-- end REF_DRIVER_CALLSIGN
-- begin REF_CAR_DETAILS
create table REF_CAR_DETAILS (
    ID varchar2(32),
    VERSION number(10) not null,
    CREATE_TS timestamp,
    CREATED_BY varchar2(50 char),
    UPDATE_TS timestamp,
    UPDATED_BY varchar2(50 char),
    DELETE_TS timestamp,
    DELETED_BY varchar2(50 char),
    --
    CAR_ID varchar2(32),
    DETAILS varchar2(255 char),
    --
    primary key (ID)
)^
-- end REF_CAR_DETAILS
-- begin REF_CARD
create table REF_CARD (
    ID varchar2(32),
    CATEGORY_ID varchar2(32),
    VERSION number(10),
    CREATE_TS timestamp,
    CREATED_BY varchar2(50 char),
    UPDATE_TS timestamp,
    UPDATED_BY varchar2(50 char),
    DELETE_TS timestamp,
    DELETED_BY varchar2(50 char),
    CARD_TYPE number(10),
    --
    STATE varchar2(255 char),
    DESCRIPTION varchar2(1000 char),
    CREATOR_ID varchar2(32),
    SUBSTITUTED_CREATOR_ID varchar2(32),
    PARENT_CARD_ID varchar2(32),
    HAS_ATTACHMENTS char(1),
    HAS_ATTRIBUTES char(1),
    PARENT_CARD_ACCESS char(1),
    --
    primary key (ID)
)^
-- end REF_CARD
-- begin REF_CAR
create table REF_CAR (
    ID varchar2(32),
    CATEGORY_ID varchar2(32),
    VERSION number(10),
    CREATE_TS timestamp,
    CREATED_BY varchar2(50 char),
    UPDATE_TS timestamp,
    UPDATED_BY varchar2(50 char),
    DELETE_TS timestamp,
    DELETED_BY varchar2(50 char),
    --
    VIN varchar2(255 char),
    COLOUR_ID varchar2(32),
    MODEL_ID varchar2(32),
    CAR_DOCUMENTATION_ID varchar2(32),
    TOKEN_ID varchar2(32),
    SELLER_ID number(19),
    CURRENCY_CODE varchar2(255 char),
    --
    primary key (ID)
)^
-- end REF_CAR
-- begin REF_DOC
create table REF_DOC (
    CARD_ID varchar2(32),
    --
    DOC_NUMBER varchar2(50 char),
    AMOUNT number(19, 2),
    --
    primary key (CARD_ID)
)^
-- end REF_DOC
-- begin REF_PLANT_MODEL_LINK
create table REF_PLANT_MODEL_LINK (
    PLANT_ID varchar2(32),
    MODEL_ID varchar2(32),
    primary key (PLANT_ID, MODEL_ID)
)^
-- end REF_PLANT_MODEL_LINK
